plugins:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "db/schema.rb"
    - "db/migrate/*"
    - "bin/**/*"
    - "vendor/**/*"
    - "node_modules/**/*"

# Rails
Rails:
  Enabled: true

# Style
Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

# Metrics
Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "config/**/*"
    - "lib/tasks/**/*"

Metrics/MethodLength:
  Max: 15

Metrics/ClassLength:
  Max: 150

# RSpec
RSpec/ExampleLength:
  Max: 15

RSpec/MultipleExpectations:
  Max: 5

RSpec/NestedGroups:
  Max: 4

# Layout
Layout/LineLength:
  Max: 120
